# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
    push:
        branches: [master, next, beta, alpha]
    pull_request:
        branches: [master, next, beta, alpha]

permissions:
    packages: write
    contents: write
    issues: write
    pull-requests: write

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x, 18.x]

        steps:
            - uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - uses: actions-rs/toolchain@v1
              with:
                toolchain: stable

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: |
                  npm ci

            - name: Build package
              run: |
                  npm run build-release

            - name: Test package
              run: |
                  npm run test

            - name: Release
              if: ${{ matrix.node-version == '16.x' }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release
